### ISSUE TITLE
Custom Activity Issue

### ISSUE THREAD

**Issue by fchauvin** [GetStream/stream-swift#12]
Hi there!

I'm attempting to add a custom activity type, by subclassing `Activity`, but there seems to be inconsistencies between the [guides](https://getstream.io/docs/swift/) and the repo.  

The [guides](https://getstream.io/docs/swift/) say that `actor` should be a string, and the example subclass in `Custom Fields`, takes in string as an actor, as seen by the super.init call. However the repo seems to force actor to be a `User`. This causes issues with our backend as we have our actors as strings, and not objects.

How can I specify the `actor` to be a `String` and not a `User`.

Thanks!

**Comment by fchauvin** [comment]
Or is it meant to create a subclass of `EnrichedActivity` by specifying the `ActorType` as a `String`? The guide should be updated if so!

**Comment by buh** [comment]
Hi @fchauvin!
Thanks! Yes, we'll update docs. 
In the `Activity` type, the `actor` by default is a `User`, because feeds by default make enrich requests. The `Activity` itself is a [typealias](https://github.com/GetStream/stream-swift/blob/master/Sources/Core/Activity/Activity.swift) from `EnrichedActivity`. You right, you need to use `EnrichedActivity` directly for your custom activity. Please, additionally check wiki pages [here](https://github.com/GetStream/stream-swift/wiki/Activities).
