### ISSUE TITLE
Error adding like reaction

### ISSUE THREAD

**Issue by HernanPaez** [GetStream/stream-swift#4]
```swift
            client.add(reactionTo: activity.id, kindOf: "like", completion: { (_) in
                completion()
            })
```

## What did you do?
Add a 'Like' reaction to an activity
## What did you expect to happen?
Add the like reaction
## What happened instead?
Fails with error:
```
{"detail":"Errors for fields 'user_id'","status_code":400,"code":4,"exception":"InputException","exception_fields":{"user_id":["user_id is a required field"]},"duration":"0.17ms"}
```
## GetStream Environment
**GetStream version: 1.1.8**
**Xcode version: 10.2**
**Swift version: 4.2**
**Platform(s) running GetStream: iOS**
**macOS version running Xcode: Mojave 10.14.4**

**Comment by buh** [comment]
@HernanPaez I'll take a look.

**Comment by buh** [comment]
@HernanPaez Could you tell me more what do you want to fix with backticks? 

The error message is about missing `user_id` and it's because you are trying to use server-side Token, instead of client side. The client-side Token should have a payload with `user_id` value only.
Please check docs here: https://getstream.io/docs_rest/#clientside_authentication

**Comment by HernanPaez** [comment]
I will check it out!

**Comment by HernanPaez** [comment]
@buh . We fixed it. We were using the server-side token. It worked again when we fixed it on the backend.
